global:
  scrape_interval: 5s
  scrape_timeout: 3s
  evaluation_interval: 10s
alerting:
  alertmanagers:
    - static_configs:
        - targets: [ ]
      scheme: http
      timeout: 10s
      api_version: v1
scrape_configs:
  - job_name: service
    scrape_interval: 1s
    metrics_path: /metrics
    static_configs:
      - targets: [ service:8080 ]
        labels:
          group: 'service'